# Generated by Django 5.2.5 on 2025-08-20 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_payment_paymenttransaction_subscriptionplan_and_more'),
        ('trip', '0002_alter_triptag_triptag_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الخطة')),
                ('duration_days', models.IntegerField(choices=[(3, '3 أيام'), (7, '7 أيام'), (30, '30 يوم')], verbose_name='مدة الترويج بالأيام')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('currency', models.CharField(default='EGP', max_length=3, verbose_name='العملة')),
                ('reach_multiplier', models.CharField(choices=[('2x', '2x'), ('3x', '3x'), ('5x', '5x')], max_length=10, verbose_name='مضاعف الوصول')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='المميزات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'خطة ترويج',
                'verbose_name_plural': 'خطط الترويج',
                'ordering': ['duration_days', 'price'],
                'indexes': [models.Index(fields=['is_active'], name='promotions__is_acti_d68947_idx'), models.Index(fields=['duration_days'], name='promotions__duratio_0ea312_idx'), models.Index(fields=['price'], name='promotions__price_5d6911_idx')],
            },
        ),
        migrations.CreateModel(
            name='PromotionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_message', models.TextField(blank=True, help_text='نبذة عن سبب الترويج (اختياري)', max_length=500, verbose_name='رسالة الراعي')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('active', 'نشط'), ('expired', 'منتهي'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرفض')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('clicks_count', models.PositiveIntegerField(default=0, verbose_name='عدد النقرات')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_promotion_requests', to=settings.AUTH_USER_MODEL, verbose_name='صاحب الرحلة')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.payment', verbose_name='الدفعة')),
                ('promotion_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.promotionplan', verbose_name='خطة الترويج')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_promotions', to=settings.AUTH_USER_MODEL, verbose_name='الراعي')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_requests', to='trip.trip', verbose_name='الرحلة')),
            ],
            options={
                'verbose_name': 'طلب ترويج',
                'verbose_name_plural': 'طلبات الترويج',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ العمولة')),
                ('currency', models.CharField(default='EGP', max_length=3, verbose_name='العملة')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('paid', 'مدفوعة'), ('cancelled', 'ملغية')], default='pending', max_length=20, verbose_name='حالة العمولة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_commissions', to=settings.AUTH_USER_MODEL, verbose_name='صاحب الرحلة')),
                ('promotion_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='promotions.promotionrequest', verbose_name='طلب الترويج')),
            ],
            options={
                'verbose_name': 'عمولة ترويج',
                'verbose_name_plural': 'عمولات الترويج',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivePromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_score', models.IntegerField(default=0, verbose_name='نقاط الأولوية')),
                ('promotion_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_promotion', to='promotions.promotionrequest', verbose_name='طلب الترويج')),
            ],
            options={
                'verbose_name': 'ترويج نشط',
                'verbose_name_plural': 'ترويجات نشطة',
                'ordering': ['-priority_score'],
            },
        ),
        migrations.AddIndex(
            model_name='promotionrequest',
            index=models.Index(fields=['sponsor', 'status'], name='promotions__sponsor_e96bfd_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionrequest',
            index=models.Index(fields=['owner', 'status'], name='promotions__owner_i_38ebe4_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionrequest',
            index=models.Index(fields=['trip', 'status'], name='promotions__trip_id_54e2ce_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionrequest',
            index=models.Index(fields=['status', 'start_date'], name='promotions__status_8931e8_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionrequest',
            index=models.Index(fields=['status', 'end_date'], name='promotions__status_6fafac_idx'),
        ),
        migrations.AddConstraint(
            model_name='promotionrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'approved', 'active'])), fields=('sponsor', 'trip'), name='unique_active_promotion_per_sponsor_trip'),
        ),
        migrations.AddIndex(
            model_name='promotioncommission',
            index=models.Index(fields=['owner', 'status'], name='promotions__owner_i_b55e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='promotioncommission',
            index=models.Index(fields=['status', 'created_at'], name='promotions__status_2fcf75_idx'),
        ),
        migrations.AddIndex(
            model_name='activepromotion',
            index=models.Index(fields=['priority_score'], name='promotions__priorit_bbd7b1_idx'),
        ),
    ]
