# Generated by Django 5.2.5 on 2025-08-19 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, max_length=15, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, max_length=15, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username can only contain letters, numbers, underscores, and hyphens.', regex='^[a-zA-Z0-9_-]+$')], verbose_name='username'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['first_name'], name='accounts_pr_first_n_dcdc7f_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['last_name'], name='accounts_pr_last_na_4157a5_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['first_name', 'last_name'], name='accounts_pr_first_n_61792f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='accounts_us_usernam_c0ea66_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_verified', 'is_active'], name='accounts_us_is_veri_edfcce_idx'),
        ),
    ]
