# Generated by Django 5.2.5 on 2025-08-20 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_first_name_alter_profile_last_name_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('currency', models.CharField(default='EGP', max_length=3, verbose_name='currency')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='status')),
                ('paymob_order_id', models.CharField(blank=True, max_length=100, verbose_name='PayMob order ID')),
                ('paymob_transaction_id', models.CharField(blank=True, max_length=100, verbose_name='PayMob transaction ID')),
                ('payment_token', models.CharField(blank=True, max_length=500, verbose_name='payment token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_data', models.JSONField(blank=True, default=dict, verbose_name='webhook data')),
                ('hmac_signature', models.CharField(blank=True, max_length=500, verbose_name='HMAC signature')),
                ('gateway_response', models.JSONField(blank=True, default=dict, verbose_name='gateway response')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='plan name')),
                ('plan_type', models.CharField(choices=[('premium', 'Premium'), ('pro', 'Pro')], max_length=20, verbose_name='plan type')),
                ('duration', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20, verbose_name='duration')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('currency', models.CharField(default='EGP', max_length=3, verbose_name='currency')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='features')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='subscription end date'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('pro', 'Pro')], default='free', max_length=20, verbose_name='subscription plan'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='subscription start date'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['subscription_plan'], name='accounts_us_subscri_be768c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['subscription_end_date'], name='accounts_us_subscri_2bb0fb_idx'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='accounts.payment'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['plan_type', 'duration'], name='accounts_su_plan_ty_963cf4_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['is_active'], name='accounts_su_is_acti_c44b39_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionplan',
            unique_together={('plan_type', 'duration')},
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.subscriptionplan'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='accounts_pa_user_id_618f05_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['paymob_order_id'], name='accounts_pa_paymob__14052f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['paymob_transaction_id'], name='accounts_pa_paymob__64803c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='accounts_pa_created_c3fc2c_idx'),
        ),
    ]
