# Generated by Django 5.2.5 on 2025-08-22 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_payment_paymenttransaction_subscriptionplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.subscriptionplan'),
        ),
    ]
