# Generated by Django 5.2.5 on 2025-08-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triptag',
            name='tripTag',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='triptag',
            index=models.Index(fields=['tripTag'], name='trip_tripta_tripTag_f77e54_idx'),
        ),
        migrations.AddIndex(
            model_name='triptag',
            index=models.Index(fields=['trip', 'tripTag'], name='trip_tripta_trip_id_be8755_idx'),
        ),
    ]
