# Generated by Django 5.2.5 on 2025-08-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_alter_triptag_triptag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='city',
            field=models.CharField(blank=True, help_text='اسم المدينة', max_length=100),
        ),
        migrations.AddField(
            model_name='trip',
            name='country',
            field=models.CharField(blank=True, help_text='اسم الدولة', max_length=100),
        ),
        migrations.AddField(
            model_name='trip',
            name='tourism_info',
            field=models.JSONField(blank=True, default=dict, help_text='معلومات سياحية شاملة من AI'),
        ),
    ]
